spring:
  datasource:
    password: Vusal2017
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      dll-auto:none

#  mvc:
#    pathmatch:
#      matching-strategy:ANT_PATH_MATCHER

server:
  port: 8082